### ISSUE TITLE
Cannot export empty labels

### ISSUE THREAD

**Issue by danilopeixoto** [wavefrontHQ/wavefront-collector-for-kubernetes#513]
We may have detected the Wavefront Collector cannot export empty labels? Is it by design?

**Comment by Jyuqi** [comment]
Hello @danilopeixoto , could you give us more details on your use case and how it relates to exporting empty labels?

**Comment by danilopeixoto** [comment]
Hi @Jyuqi,

Here is a partial pod specification:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: server-username
  namespace: multiserver-prod
  uid: 71663ca5-4c10-4541-a7cc-a50f660cc671
  resourceVersion: '501805732'
  creationTimestamp: '2022-10-10T18:40:56Z'
  labels:
    app: multiservers
    chart: multiservers-1.0.0
    component: server
    heritage: multiservers
    hub.jupyter.org/network-access-hub: 'true'
    hub.jupyter.org/servername: ''
    hub.jupyter.org/username: username
    release: multiservers
```

The label ` hub.jupyter.org/servername` is not available in Wavefront. This means we cannot query by empty tag `hub.jupyter.org/servername=''`.

**Comment by johncornish** [comment]
Hi @danilopeixoto , tags with empty values are removed because of problems that have consistently arisen from having too many tags on a metric; is there any way you can work around this? Perhaps by putting a different value in there that would represent empty

https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes/blob/d38798181b57949f7b0235a63408b7cad2157ad0/plugins/sinks/wavefront/utils.go#L12-L28

**Comment by danilopeixoto** [comment]
Thanks for confirming that. We can handle that internally.
